
name: "unit tests"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: claudiamatosa/github-action-replace-pr-body@v1.0.0-test.1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
